# Site
title:              Musing ar Lekha
bio:                'Soham: Notes, Stories and Projects'
description:        "Soham's Notes, Stories and Projects"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
disqusurl: "https://sgsen.github.io"

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

#Collections
collections:
    stories:
        output: true
        permalink: /stories/:title/

    projects:
        output: true
        permalink: /projects/:title/

# Comments
disqus_shortname:   sgsen

# Social
analytics-id:       UA-9239034-4
twitter:            sohamgsen
linkedin:           in/sohamsen
instagram:          soham.sen
github:             sgsen

# personal
location:           Bangalore, India
phone:
email:              sohamgsen+github@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://sgsen.github.io

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
